services:
  - type: web
    name: heart-disease-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: MONGO_URI
        sync: false
    autoDeploy: true